[package]
name = "box"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
logos = "0.12"
codespan-reporting = "0.11"
heck = "0.3"
bumpalo = "3.9"
